// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.BotTest.commands;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc0.BotTest.Robot;


public class Drive extends Command {
	
	private double steps = 5;
	
	double currentRightSpeed = 0;
    double currentLeftSpeed = 0;
	double fullRightSpeed = 0;
	double fullLeftSpeed = 0;
	double rightSpeedDifference = 0;
	double leftSpeedDifference = 0;
	double leftSpeedIncrement = 0;
	double rightSpeedIncrement = 0;

	public Drive() {
		requires(Robot.chasis);
	}
   
	protected void initialize() {
    }
    
	protected void execute() {
    	
    	fullLeftSpeed = Robot.oi.getLeftSpeed();
    	fullRightSpeed = Robot.oi.getRightSpeed();
    	
    	rightSpeedDifference = fullRightSpeed - currentRightSpeed;
    	leftSpeedDifference = fullRightSpeed - currentRightSpeed;
    	
    	rightSpeedIncrement = rightSpeedDifference / steps;
    	leftSpeedIncrement = leftSpeedDifference / steps;
    	
    	currentRightSpeed += rightSpeedIncrement;
    	currentLeftSpeed += leftSpeedIncrement;
    	
    	Robot.chasis.move(currentRightSpeed, currentLeftSpeed);
    	
    	if (Robot.chasis.stafeSolenoid.get() != DoubleSolenoid.Value.kForward) {
    		Robot.chasis.chasisStrafe(Robot.oi.rightJoy.getX());
    	}
    	
    }
    protected boolean isFinished() {
        return false;
    }
    protected void end() {
    	Robot.chasis.stop();
    }
    protected void interrupted() {
    }
}
