// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc0.BotTest.commands;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc0.BotTest.Robot;

/**
 *
 */
public class Strafe extends Command {
	// Whether or not to extend the strafe
	boolean Extend;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Strafe() { 
    	requires(Robot.chasis);  //Needs chasis subsystem
    	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	// Checks if solenoid is active
    	if (Robot.chasis.stafeSolenoid.get() != DoubleSolenoid.Value.kForward) {
    		// Sets extend to true if solenoid is not already active
    		Extend = true;
    	} else {
    		// Sets extend of false if solenoid is active
    		Extend = false;
    	}
    	if(Extend==true) {
    		// Sets the solenoid to active if extend is true
    		Robot.chasis.stafeSolenoid.set(DoubleSolenoid.Value.kForward);
    	} else {
    		// Sets the solenoid to not active if extend is not true
    		Robot.chasis.stafeSolenoid.set(DoubleSolenoid.Value.kReverse);
    	}
    }

    // Called repeatedly when this Command is scheduled to run
    
    protected void execute() { //This extends the strafe wheels
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.chasis.stafeSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
